version: '3.8'

services:
  monolith:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: monolith
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      - labpro-net

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=labpro-monolith
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
    networks:
      - labpro-net

networks:
  labpro-net:
    name: "labpro-network"
    