version: "3.8"
services:
    php:
        container_name: php
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        env_file: .env
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 9000:8080
        depends_on:
            - mysql-db
        networks:
            - labpro-net

    mysql-db:
        image: mysql:8
        container_name: mysql-db
        volumes:
            - ./run/var:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=securerootpassword
            - MYSQL_DATABASE=labpro-monolith
            - MYSQL_USER=dbuser
            - MYSQL_PASSWORD=secret
        networks:
            - labpro-net

networks:
  labpro-net:
    name: "labpro-network"